#!/usr/bin/env bash

set -e

version=$1
dev=$HOME/dev
this=$dev/eztrack-$version

# unpack
mkdir -p $this
tar xvf $dev/eztrack-$version.tgz -C $this
rm $dev/eztrack-$version.tgz

# link new application version
ln -sfn $this $dev/eztrack

# link enduring 'output' and 'data' directories
ln -sfn $dev/output $this/output
ln -sfn $dev/data   $this/data

# build mef lib tools
cd $this/mef_lib_2_1 && make clean all

# smoke tests
cd $this
. .env
make check-deps

printf "\n==========================\n"
printf "\nINSTALLATION SUCCESSFUL\nEZTrack updated to $version\n"
printf "\n==========================\n\n"
