#!/usr/bin/env bash

set -eu

version=$1
dest=$2

this=$dest/eztrack-$version

echo "Installing $version to $dest..."

# unpack
mkdir -p $this
tar xvf $dest/eztrack-$version.tgz -C $this
rm $dest/eztrack-$version.tgz

# link new application version
ln -sfn $this $dest/eztrack

# link enduring 'output' and 'data' directories
ln -sfn $dest/output $this/output
ln -sfn $dest/data   $this/data

# build mef lib tools
cd $this/mef_lib_2_1 && make clean all

# smoke tests
cd $this
. .env
make check-deps

printf "\n=============================\n"
printf "\nINSTALLATION SUCCESSFUL\nEZTrack updated to $version\n"
printf "\n=============================\n\n"
