patients = {,...
%     'pt1sz2', 'pt1sz3', 'pt1sz4',...
%     'pt2sz1' 'pt2sz3' 'pt2sz4', ...
%     'pt3sz2' 'pt3sz4', ...
%     'pt6sz3', 'pt6sz4', 'pt6sz5', ...
%     'pt8sz1' , 'pt8sz2','pt8sz3',...
%     'pt10sz1', 'pt10sz2' 'pt10sz3', ...
%     'pt7sz19', 'pt7sz21', 'pt7sz22',...
%     'pt11sz1', 'pt11sz2' 'pt11sz3' 'pt11sz4', ...
%     'pt12sz1', 'pt12sz2', ...
%     'pt13sz1', 'pt13sz2', 'pt13sz3', 'pt13sz5',...
%     'JH101sz1' 
%     'JH101sz2' 'JH101sz3' 'JH101sz4',...
% 	'JH102sz1' 'JH102sz2' 'JH102sz3' 'JH102sz4' 'JH102sz5' 'JH102sz6',...
% 	'JH103sz1' 'JH103sz2' 'JH103sz3',...
% 	'JH104sz1' 'JH104sz2' 'JH104sz3',...
% 	'JH105sz1' 'JH105sz2' 'JH105sz3' 'JH105sz4' 'JH105sz5',...
% 	'JH106sz1' 'JH106sz2' 'JH106sz3' 'JH106sz4' 'JH106sz5' 'JH106sz6',...
% 	'JH107sz1' 'JH107sz2' 'JH107sz3' 'JH107sz4' 'JH107sz5' 'JH107sz6' 'JH107sz7' 'JH107sz8' 'JH107sz8', 'JH107sz9'...
%     'JH108sz1', 'JH108sz2', 'JH108sz3', 'JH108sz4', 'JH108sz5', 'JH108sz6', 'JH108sz7',...
%     'UMMC001_sz1', 'UMMC001_sz2', 'UMMC001_sz3', ...
%     'UMMC002_sz1', 'UMMC002_sz2', 'UMMC002_sz3', ...
%     'UMMC003_sz1', 'UMMC003_sz2', 'UMMC003_sz3', ...
%     'UMMC004_sz1', 'UMMC004_sz2', 'UMMC004_sz3', ...
%     'UMMC005_sz1', 'UMMC005_sz2', 'UMMC005_sz3', ...
%     'UMMC006_sz1', 'UMMC006_sz2', 'UMMC006_sz3', ...
%     'UMMC007_sz1', 'UMMC007_sz2', 'UMMC007_sz3', ...
%     'UMMC008_sz1', 'UMMC008_sz2', 'UMMC008_sz3', ...
%     'UMMC009_sz1', 'UMMC009_sz2', 'UMMC009_sz3', ...
%     'EZT007_seiz001', 'EZT007_seiz002', 'EZT007_seiz003',...
%     'EZT019_seiz001', 'EZT019_seiz002', 'EZT019_seiz003',...
%     'EZT090_seiz001', 'EZT090_seiz002', 'EZT090_seiz003',...
%     'EZT091_seiz001', 'EZT091_seiz002', 'EZT091_seiz003',...
%     'EZT092_seiz001', 'EZT092_seiz002', 'EZT092_seiz003',...
%     'EZT108_seiz001', 'EZT108_seiz002',...
%     'EZT120_seiz001', 'EZT120_seiz002', 'EZT120_seiz003',...
%     'EZT121_seiz001', 'EZT121_seiz002', 'EZT121_seiz003',...
    'EZT127_seiz001', 'EZT127_seiz002',...
};

close all;
% data directories to save data into - choose one
eegRootDirHD = '/Volumes/NIL Pass/';
eegRootDirHD = '/Volumes/ADAM LI/';
eegRootDirServer = '/home/ali/adamli/fragility_dataanalysis/';                 % at ICM server 
eegRootDirHome = '/Users/adam2392/Documents/adamli/fragility_dataanalysis/';   % at home macbook
eegRootDirJhu = '/home/WIN/ali39/Documents/adamli/fragility_dataanalysis/';    % at JHU workstation
eegRootDirMarcctest = '/home-1/ali39@jhu.edu/work/adamli/fragility_dataanalysis/'; % at MARCC server
eegRootDirMarcc = '/scratch/groups/ssarma2/adamli/fragility_dataanalysis/';

% Determine which directory we're working with automatically
if     ~isempty(dir(eegRootDirServer)), rootDir = eegRootDirServer;
% elseif ~isempty(dir(eegRootDirHD)), rootDir = eegRootDirHD;
elseif ~isempty(dir(eegRootDirHome)), rootDir = eegRootDirHome;
elseif ~isempty(dir(eegRootDirJhu)), rootDir = eegRootDirJhu;
elseif ~isempty(dir(eegRootDirMarcc)), rootDir = eegRootDirMarcc;
else   error('Neither Work nor Home EEG directories exist! Exiting'); end

% Determine which data directory we're working with automatically
if     ~isempty(dir(eegRootDirServer)), dataDir = eegRootDirServer;
elseif ~isempty(dir(eegRootDirHD)), dataDir = eegRootDirHD;
elseif ~isempty(dir(eegRootDirJhu)), dataDir = eegRootDirJhu;
elseif ~isempty(dir(eegRootDirMarcc)), dataDir = eegRootDirMarcc;
else   error('Neither Work nor Home EEG directories exist! Exiting'); end

addpath(genpath(fullfile(rootDir, '/fragility_library/')));
addpath(genpath(fullfile(rootDir, '/eeg_toolbox/')));
addpath(rootDir);

for iPat=1:length(patients)
    patient = patients{iPat};
    
    [~, patient_id, seizure_id, seeg] = splitPatient(patient);
    
    [included_channels, ezone_labels, earlyspread_labels, latespread_labels, resection_labels, frequency_sampling, center] ...
        = determineClinicalAnnotations(patient_id, seizure_id);
    
    % set dir to find raw data files
    patDir = fullfile(dataDir, '/data/', center);
    
    outputpath = fullfile('/Volumes/ADAM LI/eztrack/output/eeg', patient);
    if ~exist(outputpath, 'dir')
        mkdir(outputpath);
    end
    
    %% Read in EEG Raw Data and Preprocess
    if seeg
        patient_eeg_path = fullfile(patDir, patient_id);
    %     patient = strcat(patient_id, seizure_id); % for EZT pats
    else
        patient_eeg_path = fullfile(patDir, patient);
    end

    clear eeg
    fprintf('Loading data...\n');
    % READ EEG FILE Mat File
    % files to process
    data = load(fullfile(patient_eeg_path, strcat(patient, '.mat')));
    
    % if NIH, UMMC, new JHU, new CC data
    eeg = data.data;
    avg = mean(eeg, 1);
    eeg = eeg-avg;
    eeg = eeg';
    labels = data.elec_labels;
    
%     engelscore = data.engelscore;
%     frequency_sampling = data.fs;
%     outcome = data.outcome;
%     seizure_eonset_ms = data.seizure_eonset_ms;
%     seizure_eoffset_ms = data.seizure_eoffset_ms;
%     seizure_conset_ms = data.seizure_conset_ms;
%     seizure_coffset_ms = data.seizure_coffset_ms;
    fprintf('Loaded data...\n');
    clear data

    labels_file = fullfile(outputpath, strcat(patient, '_labels.csv'));
    labels_file_id = fopen(labels_file, 'w');
    fprintf(labels_file_id, strjoin(labels,','));
    fclose(labels_file_id);
    
    eeg_file = fullfile(outputpath, strcat(patient, '_eeg.csv'));
    dlmwrite(eeg_file, eeg, 'delimiter', ',', 'precision', '%.7f');
end