#!/usr/bin/env bash

set -e

# Usage: ./downsample path/to/mef.txt
# save path and filename
# get the filename without the extension
# add downsampled.
full_filename=$(basename "$1")
extension="${full_filename##*.}"
filename="${full_filename%.*}"
dir=$(dirname "$1")

echo "downsampling $full_filename"

# Downsample by 50%
awk 'NR % 2 == 0' $1 > $dir/${filename}_downsample.$extension

# Remove the original file to conserve disk space
rm $1
