#!/usr/bin/env bash

set -e

# save path and filename
# get the filename without the extension
# add downsampled.
full_filename=$(basename "$1")
extension="${full_filename##*.}"
filename="${full_filename%.*}"
dir=$(dirname "$1")

start=$2
end=$3

echo "time_filter $full_filename"

tail -n +$start $1 | head -n $3 > $dir/${filename}_window.$extension

# Remove the original file to conserve disk space
rm $1
