#!/usr/bin/env bash

set -e

PROJECT_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mef_path=$PROJECT_HOME/../mef_lib_2_1

matlab_exe="/Applications/MATLAB_R2014b.app/bin/matlab"
matlab_jvm="$matlab_exe -nodesktop -nosplash -r"

heatmap_output=$PROJECT_HOME/output/heatmap
temporal_out=/tmp/eztrack-temporal
reference=$PROJECT_HOME/data/reference

patient_id=$1
[[ ! -z "$patient_id" ]] || { echo "Usage: ./eztrack <patient_id (e.g. PY12N008)>" ; exit 1 ; }

eeg2fsv_out=$PROJECT_HOME/output/eeg/$patient_id/adj_pwr
reference_heatmap=${patient_id}_iEEG_temporal_results_28-Aug-2015.csv

[[ ! -z "`which $matlab_exe`" ]] || \
    { echo "MATLAB not found at $matlab_exe; please check the Getting Started section in the README" ; exit 1 ; }

[[ -d $reference ]] || \
    { echo "EZTrack reference data not found at $reference; please check the Getting Started section in the README" ; exit 1 ; }

# TODO: Map patient_id to $patient_id.csv saved to $PROJECT_HOME
printf "\n== Validating $patient_id.csv  ==\n"
echo "TODO: input validation"

printf "\n== Finding MEF files for $patient_id  ==\n"
echo "TODO: mef_finder"

printf "\n== Copying MEF files to local storage  ==\n"
echo "TODO: mef_copy"

printf "\n== Extracting signals... ==\n"
echo "TODO: mef2eeg"

printf "\n== eeg2fsv ==\n"
rm -rf $eeg2fsv_out
# TODO: Refactor to give eeg2fsv a simpler entry point with patient_id as a parameter.
cd $PROJECT_HOME/tests/eeg2fsv && $matlab_jvm "eeg2fsv_test; exit"
cp $eeg2fsv_out/svd_vectors/fsv_pwr$patient_id.mat $PROJECT_HOME/output/fsv

# fsv2heatmap currently processes all fsv's for a particular lobe.
printf "\n== fsv2heatmap ==\n"
cd $PROJECT_HOME/fsv2heatmap && \
    $matlab_jvm "csv_file = temporal_ieeg_results('$patient_id'); display(csv_file); exit" > /tmp/eztrack-temporal

# TODO: Have fsv2heatmap save this output path to a different file.
results=`tail -n 3 $temporal_out | head -n 1`

# TODO: temporary tests for development
git co $PROJECT_HOME/output/fsv
echo "Validating fsv2heatmap results at $results"
diff $results $heatmap_output/$reference_heatmap
printf "\tAll tests passed: Results match reference heatmap.\n"
### End of development testing.

printf "EZTrack finished: Results saved to\n$results\n"


