% %% Import data from spreadsheet
% % Script for importing data from the following spreadsheet:
% %
% %    Workbook: /Users/adam2392/Dropbox/EZTrack/PAPER/Data/nih/pt1_iEEG_temporal_results_08-Jun-2016.xlsx
% %    Worksheet: combined results
% %
% % To extend the code for use with different selected data or a different
% % spreadsheet, generate a function instead of a script.
% 
% % Auto-generated by MATLAB on 2017/03/20 19:55:56
% 
% %% Import the data
% [~, ~, raw] = xlsread('/Users/adam2392/Dropbox/EZTrack/PAPER/Data/nih/pt2_iEEG_temporal_results_09-Jun-2016.xlsx';
% raw = raw(2:end,:);
% raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
% cellVectors = raw(:,1);
% raw = raw(:,[2,3,4,5,6,7,8]);
% 
% %% Replace non-numeric cells with NaN
% R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
% raw(R) = {NaN}; % Replace non-numeric cells
% 
% %% Create output variable
% data = reshape([raw{:}],size(raw));
% 
% %% Allocate imported array to column variable names
% label = cellVectors(:,1);
% sz2_weight = data(:,1);
% sz3_weight = data(:,2);
% sz4_weight = data(:,3);
% sz6_weight = data(:,4);
% averageweight = data(:,5);
% 
% E_gauss1 = sz2_weight;
% E_gauss2 = sz3_weight;
% E_gauss3 = sz4_weight;
% E_gauss4 = sz6_weight;
% E_Weights = averageweight;
% E_labels = label;
% 
% save('pt1', 'E_gauss1', 'E_gauss2', 'E_gauss3', 'E_gauss4', 'E_Weights', 'E_labels');
% 
% %% Clear temporary variables
% clearvars data raw cellVectors R;

%% pt2
%% Import the data
% [~, ~, raw] = xlsread('/Users/adam2392/Dropbox/EZTrack/PAPER/Data/nih/pt2_iEEG_temporal_results_09-Jun-2016.xlsx','combined results');
% raw = raw(2:end,:);
% raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
% cellVectors = raw(:,1);
% raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13]);
% 
% %% Create output variable
% data = reshape([raw{:}],size(raw));
% 
% %% Allocate imported array to column variable names
% label1 = cellVectors(:,1);
% sz1_weight = data(:,1);
% sz1_heatmap_color = data(:,2);
% sz1_rank = data(:,3);
% sz3_weight1 = data(:,4);
% sz3_heatmap_color = data(:,5);
% sz3_rank = data(:,6);
% sz4_weight1 = data(:,7);
% sz4_heatmap_color = data(:,8);
% sz4_rank = data(:,9);
% averageweight1 = data(:,10);
% averagecolor = data(:,11);
% averagerank = data(:,12);
% 
% E_gauss1 = sz1_weight;
% E_gauss2 = sz3_weight;
% E_gauss3 = sz4_weight;
% E_Weights = averageweight1;
% E_labels = label1;
% 
% save('pt2', 'E_gauss1', 'E_gauss2', 'E_gauss3', 'E_Weights', 'E_labels');
% 
% 
% %% Clear temporary variables
% clearvars data raw cellVectors;
%% Import the data
[~, ~, raw] = xlsread('/home/WIN/ali39/Dropbox/EZTrack/PAPER/Data/ummc/ummc008_iEEG_results.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,4,6]);
raw = raw(:,[3,5,7,8]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
patient_id = cellVectors(:,1);
label = cellVectors(:,2);
weight_sz1 = data(:,1);
label1 = cellVectors(:,3);
weight_sz2 = data(:,2);
label2 = cellVectors(:,4);
weight_sz3 = data(:,3);
weight = data(:,4);

E_gauss1 = weight_sz1;
E_gauss2 = weight_sz2;
E_gauss3 = weight_sz3;
E_Weights = weight;
E_labels = label;

% 
save('ummc008', 'E_gauss1', 'E_gauss2', 'E_gauss3', 'E_Weights', 'E_labels');

%% Clear temporary variables
clearvars data raw cellVectors R;
clear all